services:
  wishlist-service:
    image: openjdk:17-jdk-slim
    container_name: wishlist-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/wishlist
    depends_on:
      - mongo
    networks:
      - wishlist-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wishlist-network

volumes:
  mongo-data:

networks:
  wishlist-network:
    driver: bridge